
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'asignacion coma cssTags dosPuntos entradas formato_hexadecimal generar_CSS htmlTags interpretar_etiqueta interpretar_propiedad let llaveApertura llaveCierre num parDer parIzq procesosS : INICIO ENTRADA PROCESOS FININICIO : llaveAperturaENTRADA : INPUT dosPuntos LISTA_IDINPUT : entradasLISTA_ID : ID_NUM RESTO_LISTAID_NUM : DIGITO RESTO_ID_NUMRESTO_ID_NUM : DIGITO RESTO_ID_NUM\n    | vacioRESTO_LISTA : coma RESTOZRESTOZ : ID_NUM RESTO_LISTA\n    | ETIQUETA coma PROPIEDADPROCESOS : P dosPuntos EXPRESIONP : procesosID_TEXT : LETRA RESTO_ID_TEXTRESTO_ID_TEXT : LETRA RESTO_ID_TEXT\n    | DIGITO RESTO_ID_TEXT\n    | vacioEXPRESION : ID_TEXT asignacion RESTOX\n    | FUNCION_INTERNA_4 parIzq ID_TEXT coma ID_TEXT coma ID_TEXT parDerRESTOX : FUNCION_INTERNA_1 parIzq ID_NUM coma ID_NUM coma ID_NUM parDer EXPRESION\n    | FUNCION_INTERNA_2 parIzq ETIQUETA parDer EXPRESION\n    | FUNCION_INTERNA_3 parIzq PROPIEDAD parDer EXPRESIONFUNCION_INTERNA_1 : formato_hexadecimalFUNCION_INTERNA_2 : interpretar_etiquetaFUNCION_INTERNA_3 : interpretar_propiedadFUNCION_INTERNA_4 : generar_CSSPROPIEDAD : cssTagsETIQUETA : htmlTagsLETRA : letDIGITO : numFIN : llaveCierrevacio : '
    
_lr_action_items = {'llaveApertura':([0,],[3,]),'$end':([1,11,12,],[0,-1,-31,]),'entradas':([2,3,],[6,-2,]),'procesos':([4,14,24,35,50,56,57,],[9,-3,-5,-9,-10,-11,-27,]),'dosPuntos':([5,6,8,9,],[10,-4,13,-13,]),'llaveCierre':([7,18,40,67,68,71,74,],[12,-12,-18,-21,-22,-19,-20,]),'num':([10,16,17,21,23,25,26,31,33,52,62,70,],[17,17,-30,17,-29,17,17,17,17,17,17,17,]),'generar_CSS':([13,63,64,73,],[22,22,22,22,]),'let':([13,17,21,23,30,31,33,55,63,64,65,73,],[23,-30,23,-29,23,23,23,23,23,23,23,23,]),'coma':([15,16,17,21,23,26,27,28,31,32,33,34,36,37,38,39,47,48,49,58,61,66,],[25,-32,-30,-32,-29,-32,-6,-8,-32,-14,-32,-17,25,51,-28,-7,55,-15,-16,62,65,70,]),'parDer':([16,17,21,23,26,27,28,31,32,33,34,38,39,48,49,57,59,60,69,72,],[-32,-30,-32,-29,-32,-6,-8,-32,-14,-32,-17,-28,-7,-15,-16,-27,63,64,71,73,]),'asignacion':([17,19,21,23,31,32,33,34,48,49,],[-30,29,-32,-29,-32,-14,-32,-17,-15,-16,]),'parIzq':([20,22,41,42,43,44,45,46,],[30,-26,52,53,54,-23,-24,-25,]),'htmlTags':([25,53,],[38,38,]),'formato_hexadecimal':([29,],[44,]),'interpretar_etiqueta':([29,],[45,]),'interpretar_propiedad':([29,],[46,]),'cssTags':([51,54,],[57,57,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'INICIO':([0,],[2,]),'ENTRADA':([2,],[4,]),'INPUT':([2,],[5,]),'PROCESOS':([4,],[7,]),'P':([4,],[8,]),'FIN':([7,],[11,]),'LISTA_ID':([10,],[14,]),'ID_NUM':([10,25,52,62,70,],[15,36,58,66,72,]),'DIGITO':([10,16,21,25,26,31,33,52,62,70,],[16,26,33,16,26,33,33,16,16,16,]),'EXPRESION':([13,63,64,73,],[18,67,68,74,]),'ID_TEXT':([13,30,55,63,64,65,73,],[19,47,61,19,19,69,19,]),'FUNCION_INTERNA_4':([13,63,64,73,],[20,20,20,20,]),'LETRA':([13,21,30,31,33,55,63,64,65,73,],[21,31,21,31,31,21,21,21,21,21,]),'RESTO_LISTA':([15,36,],[24,50,]),'RESTO_ID_NUM':([16,26,],[27,39,]),'vacio':([16,21,26,31,33,],[28,34,28,34,34,]),'RESTO_ID_TEXT':([21,31,33,],[32,48,49,]),'RESTOZ':([25,],[35,]),'ETIQUETA':([25,53,],[37,59,]),'RESTOX':([29,],[40,]),'FUNCION_INTERNA_1':([29,],[41,]),'FUNCION_INTERNA_2':([29,],[42,]),'FUNCION_INTERNA_3':([29,],[43,]),'PROPIEDAD':([51,54,],[56,60,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> INICIO ENTRADA PROCESOS FIN','S',4,'p_S','sintactico.py',7),
  ('INICIO -> llaveApertura','INICIO',1,'p_INICIO','sintactico.py',11),
  ('ENTRADA -> INPUT dosPuntos LISTA_ID','ENTRADA',3,'p_ENTRADA','sintactico.py',15),
  ('INPUT -> entradas','INPUT',1,'p_INPUT','sintactico.py',19),
  ('LISTA_ID -> ID_NUM RESTO_LISTA','LISTA_ID',2,'p_LISTA_ID','sintactico.py',23),
  ('ID_NUM -> DIGITO RESTO_ID_NUM','ID_NUM',2,'p_ID_NUM','sintactico.py',27),
  ('RESTO_ID_NUM -> DIGITO RESTO_ID_NUM','RESTO_ID_NUM',2,'p_RESTO_ID_NUM','sintactico.py',31),
  ('RESTO_ID_NUM -> vacio','RESTO_ID_NUM',1,'p_RESTO_ID_NUM','sintactico.py',32),
  ('RESTO_LISTA -> coma RESTOZ','RESTO_LISTA',2,'p_RESTO_LISTA','sintactico.py',36),
  ('RESTOZ -> ID_NUM RESTO_LISTA','RESTOZ',2,'p_RESTOZ','sintactico.py',40),
  ('RESTOZ -> ETIQUETA coma PROPIEDAD','RESTOZ',3,'p_RESTOZ','sintactico.py',41),
  ('PROCESOS -> P dosPuntos EXPRESION','PROCESOS',3,'p_PROCESOS','sintactico.py',45),
  ('P -> procesos','P',1,'p_P','sintactico.py',49),
  ('ID_TEXT -> LETRA RESTO_ID_TEXT','ID_TEXT',2,'p_ID_TEXT','sintactico.py',53),
  ('RESTO_ID_TEXT -> LETRA RESTO_ID_TEXT','RESTO_ID_TEXT',2,'p_RESTO_ID_TEXT','sintactico.py',57),
  ('RESTO_ID_TEXT -> DIGITO RESTO_ID_TEXT','RESTO_ID_TEXT',2,'p_RESTO_ID_TEXT','sintactico.py',58),
  ('RESTO_ID_TEXT -> vacio','RESTO_ID_TEXT',1,'p_RESTO_ID_TEXT','sintactico.py',59),
  ('EXPRESION -> ID_TEXT asignacion RESTOX','EXPRESION',3,'p_EXPRESION','sintactico.py',63),
  ('EXPRESION -> FUNCION_INTERNA_4 parIzq ID_TEXT coma ID_TEXT coma ID_TEXT parDer','EXPRESION',8,'p_EXPRESION','sintactico.py',64),
  ('RESTOX -> FUNCION_INTERNA_1 parIzq ID_NUM coma ID_NUM coma ID_NUM parDer EXPRESION','RESTOX',9,'p_RESTOX','sintactico.py',67),
  ('RESTOX -> FUNCION_INTERNA_2 parIzq ETIQUETA parDer EXPRESION','RESTOX',5,'p_RESTOX','sintactico.py',68),
  ('RESTOX -> FUNCION_INTERNA_3 parIzq PROPIEDAD parDer EXPRESION','RESTOX',5,'p_RESTOX','sintactico.py',69),
  ('FUNCION_INTERNA_1 -> formato_hexadecimal','FUNCION_INTERNA_1',1,'p_FUNCION_INTERNA_1','sintactico.py',73),
  ('FUNCION_INTERNA_2 -> interpretar_etiqueta','FUNCION_INTERNA_2',1,'p_FUNCION_INTERNA_2','sintactico.py',77),
  ('FUNCION_INTERNA_3 -> interpretar_propiedad','FUNCION_INTERNA_3',1,'p_FUNCION_INTERNA_3','sintactico.py',81),
  ('FUNCION_INTERNA_4 -> generar_CSS','FUNCION_INTERNA_4',1,'p_FUNCION_INTERNA_4','sintactico.py',85),
  ('PROPIEDAD -> cssTags','PROPIEDAD',1,'p_PROPIEDAD','sintactico.py',89),
  ('ETIQUETA -> htmlTags','ETIQUETA',1,'p_ETIQUETA','sintactico.py',93),
  ('LETRA -> let','LETRA',1,'p_LETRA','sintactico.py',97),
  ('DIGITO -> num','DIGITO',1,'p_DIGITO','sintactico.py',101),
  ('FIN -> llaveCierre','FIN',1,'p_FIN','sintactico.py',105),
  ('vacio -> <empty>','vacio',0,'p_vacio','sintactico.py',109),
]
